### PR TITLE
Libraries

### PR DESCRIPTION
**Pull request by CupcakeFoxxo**

### CODE REVIEW

**Comment by ahirschberg** [comment]
I'm getting the following error when running the app. How do I set my location?

```
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$99(LauncherImpl.java:182)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Location is not set.
    at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
    at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
    at fxapp.MainFXApplication.initRootLayout(MainFXApplication.java:143)
    at fxapp.MainFXApplication.start(MainFXApplication.java:53)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$106(LauncherImpl.java:863)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$119(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl.lambda$null$117(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$118(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
    ... 1 more
```

**Comment by ahirschberg** [comment]
Is this merge-ready? If so we can do a merge of master into libraries, fix the conflicts, and then merge to master

**Review by jeremydiba — APPROVED** [review]
Good.  water reports showing up as pins not implemented

**Comment by ahirschberg** [comment]
Closes issues #31, #32

**Pull request merged**
